### ISSUE TITLE
Error reported on TimeLimit settings parameter

### ISSUE THREAD

**Issue by sambuddhac** [jump-dev/HiGHS.jl#122] opened 2022-08-08 21:50 UTC
I get the following error when I have the TimeLimit parameter set to `Inf`:

```
ERROR: LoadError: MathOptInterface.SetAttributeNotAllowed{MathOptInterface.RawOptimizerAttribute}: Setting attribute MathOptInterface.RawOptimizerAttribute("time_limit") cannot be performed: 

Invalid value `Inf::String` for option "time_limit".

 You may want to use a `CachingOptimizer` in `AUTOMATIC` mode or you may need to call `reset_optimizer` before doing this operation if the `CachingOptimizer` is in `MANUAL` mode.
```

So, I set it to `false`. I then get this error:
```

ERROR: LoadError: MathOptInterface.SetAttributeNotAllowed{MathOptInterface.RawOptimizerAttribute}: Setting attribute MathOptInterface.RawOptimizerAttribute("time_limit") cannot be performed: 

Invalid value `false::Bool` for option "time_limit".

 You may want to use a `CachingOptimizer` in `AUTOMATIC` mode or you may need to call `reset_optimizer` before doing this operation if the `CachingOptimizer` is in `MANUAL` mode.
```

**Comment by odow** [comment] 2022-08-09 11:58
It looks like you set the `String` value `"Inf"`, not the `Float64` value `Inf`.

For the second error, you can't set the time limit to `false`. It needs a `Float64`, not a `Bool`.

**Comment by odow** [comment] 2022-08-16 21:10
Closing because this is not a bug in HiGHS.

**Closed by odow** 2022-08-16 21:10 UTC
